"""Event and order data structures used across the trading simulator."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Optional


class Side(str, Enum):
    """Enumerates trade sides for clarity."""

    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    """Enumerates supported order types."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


def _parse_timestamp(value: Any) -> datetime:
    if isinstance(value, datetime):
        return value.astimezone(timezone.utc)
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=timezone.utc)
    if isinstance(value, str):
        try:
            return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)
        except ValueError as exc:  # pragma: no cover - defensive guard for bad input
            raise ValueError(f"Unable to parse timestamp: {value}") from exc
    raise TypeError(f"Unsupported timestamp value: {value!r}")


@dataclass(frozen=True)
class MarketEvent:
    """Represents a snapshot of the market used for simulation."""

    symbol: str
    timestamp: datetime
    bid: float
    ask: float
    bid_size: float
    ask_size: float
    last_price: float
    last_size: float
    midpoint: float = field(init=False)

    def __post_init__(self) -> None:
        object.__setattr__(self, "midpoint", (self.bid + self.ask) / 2.0)

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "MarketEvent":
        return cls(
            symbol=payload["symbol"],
            timestamp=_parse_timestamp(payload["timestamp"]),
            bid=float(payload["bid"]),
            ask=float(payload["ask"]),
            bid_size=float(payload.get("bid_size", 0.0)),
            ask_size=float(payload.get("ask_size", 0.0)),
            last_price=float(payload.get("last_price", (payload["bid"] + payload["ask"]) / 2.0)),
            last_size=float(payload.get("last_size", 0.0)),
        )


@dataclass
class OrderRequest:
    """Represents an intent to trade generated by a strategy."""

    client_order_id: str
    symbol: str
    side: Side
    quantity: float
    order_type: OrderType
    price: Optional[float] = None
    time_in_force: str = "GTC"
    metadata: Dict[str, Any] | None = None


@dataclass
class FillEvent:
    """Represents a simulated execution result."""

    order_id: str
    symbol: str
    side: Side
    quantity: float
    price: float
    timestamp: datetime
    liquidity: str
    fees: float = 0.0
    metadata: Dict[str, Any] | None = None


__all__ = [
    "FillEvent",
    "MarketEvent",
    "OrderRequest",
    "OrderType",
    "Side",
]
